### ISSUE TITLE
Question about JSON validation: Type "object" can be null?

### ISSUE THREAD

**Issue by shonigbaum** [ISAITB/json-validator#4]
Hello,

we validated an event against a schema and it seems that the validator allows an object to be null, also we didn't allow it to be null:

If we use the following schema:
```json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "object"
		}
  	}
}
```

And validate this event against the given schema:
```json
{
	"name": null
}
```

It returns a success message. Other validators (https://www.jsonschemavalidator.net) or compilers (https://github.com/santhosh-tekuri/jsonschema) we use in our code, do not allow this.

Null is only allowed if the type would look like: `"type": ["object", "null"]`.

Is this a bug or are the other validators/compiler misinterpret the specifications?

Thanks in advance.

**Comment by costas80** [comment]
Thanks for raising this @shonigbaum. I'll replicate the scenario you highlight asap and come back to you.

Note that our JSON validator internally uses   https://github.com/networknt/json-schema-validator as the validation engine, so in the meantime you could potentially check in that repo to see if there is any relevant issue or question. In any case I'll get back to you as soon as I've had a chance to verify this.

**Comment by shonigbaum** [comment]
Thank you @costas80.
Was looking for the underlying library, hehe.
I also opened an issue on their side: https://github.com/networknt/json-schema-validator/issues/999

**Comment by costas80** [comment]
@shonigbaum, the issue in the end was not due to the underlying validation library. We were a minor version behind its latest release but updating did not resolve the issue - [this comment](https://github.com/networknt/json-schema-validator/issues/999#issuecomment-2022572852) also shows it works as expected.

The problem was in our own validator where due to the pretty-printing of provided input before validation, null values were in fact not being serialised. This has now been corrected and the validation works as expected. Trying out your sample input and schema on our [generic validator instance](https://www.itb.ec.europa.eu/json/any/upload) gives the expected result:

![image](https://github.com/ISAITB/json-validator/assets/8297297/742abb5c-36b0-47d5-b3d0-39d1d7573b3c)

The fix is already available on this repo's master branch, all our managed validators, and on the published "latest" [Docker image](https://hub.docker.com/r/isaitb/json-validator).

Could you please resolve this issue once you confirm on your end?

**Comment by shonigbaum** [comment]
Thank you, I will test it tomorrow at work. :)

**Comment by shonigbaum** [comment]
Hey @costas80,
looks good to time. :) Thank you!
